@startuml
'https://plantuml.com/state-diagram


[*] --> IHMLogin


state IHMLogin {
    state Accueil
    }

state IHMAdmin {
    state InitialisationBibliothèque
    state CréerBibliothèque
    state ImporterBibliothèque
    state BibliothèqueChargée
    state GérerLivres
    state GérerUtilisateurs
    state GérerEmprunts
   }

state IHMAdherent {
    state ChercherLivre
    state DemanderEmprunt
    state GérerProfil
   }


@enduml