@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
boundary IHM
control Controller
database Database
database Identification

User -> IHM: Authentication Request (Id, password)
IHM -> Controller: Id, password
Controller -> Identification: SELECT Password FROM Identification WHERE Id=Id
Controller <- Identification: PasswordDB
Controller <- Controller: If Password=PasswordDB : set userId to Id
IHM <- Controller: Identification succes
User <- IHM: Welcome "user"

User -> IHM: List of borrowed books request
IHM -> Controller: get list of borrowed books
Controller -> Database: SELECT * FROM ...
Controller <- Database: Data
IHM <- Controller: Callback
User <- IHM: Display data

User -> IHM: Log out
IHM -> Controller: Log out
Controller -> Controller: set userId to null
IHM <- Controller: Logged out successfully
User <- IHM: Logged out successfully

@enduml